@startuml
title Remove Book from Catalog

actor Client
participant "Load Balancer/ECS" as ECS
participant RemoveBookFromCatalogActivity
participant CatalogDao
database DynamoDB

Client -> ECS : HTTP request
activate Client
activate ECS
activate RemoveBookFromCatalogActivity
activate CatalogDao
ECS -> RemoveBookFromCatalogActivity :  execute(RemoveBookFromCatalogRequest)
RemoveBookFromCatalogActivity -> CatalogDao : removeBookFromCatalog(bookId : String)
CatalogDao -> DynamoDB : remove book by ID
alt if book ID does not exist
    CatalogDao <-- DynamoDB : null
    ECS <-- CatalogDao : throw BookNotFoundException
    Client <-- ECS : 404 Response
else otherwise, continue
end

CatalogDao <-- DynamoDB : Book Removed Successfully message
RemoveBookFromCatalogActivity <-- CatalogDao : Book Removed Successfully message
ECS <-- RemoveBookFromCatalogActivity : RemoveBookFromCatalogResponse
deactivate CatalogDao
deactivate RemoveBookFromCatalogActivity
deactivate ECS
Client <-- ECS : 200 Response
deactivate Client
@enduml